// Generated by https://quicktype.io

export interface DocResult {
    results: Result[];
    start: number;
    limit: number;
    size: number;
    _links: DocResultLinks;
}

export interface DocResultLinks {
    self: string;
    base: string;
    context: string;
}

export interface Result {
    id: number;
    key: string;
    name: string;
    type: string;
    _links: ResultLinks;
    _expandable: Expandable;
}

export interface Expandable {
    metadata: string;
    icon: string;
    description: string;
    homepage?: string;
}

export interface ResultLinks {
    webui: string;
    self: string;
}


export interface DocSaveModel {
    type: string;
    title: string;
    ancestors: Ancestor[];
    space: Space;
    body: Body;
}

export interface Ancestor {
    id: number;
}

export interface Body {
    storage: Storage;
}

export interface Storage {
    value: string;
    representation: string;
}

export interface Space {
    key: string;
}


